### ISSUE TITLE
Crashes IE11 on Win 8.1

### ISSUE THREAD

**Issue by palnes** [hyperform/hyperform#20] opened 2016-10-14 11:39 UTC
To reproduce, open:
https://hyperform.js.org/examples.html#file=types
and interact with any form element

What happens:
Internet Explorer crashes, and has to be restarted.

**Comment by Boldewyn** [comment] 2016-10-14 12:19
OK, that sounds bad. I'll investigate, thanks for the report!

**Comment by Boldewyn** [comment] 2016-10-18 07:05
I've downloaded a fresh VM from modern.ie with IE 11 and Win 8.1. Unfortunately I cannot reproduce this problem. The VM hardware settings are rather lousy, and the console shows no error whatsoever.

Do you happen to have some more debugging info? I.e., are there plugins enabled, does it happen when you switch examples or when you open the page freshly, ...?

This specific page features all new input types of HTML5. Perhaps this is some rare combo of IE11 with a certain patch level mis-interacting with a buggy control...

**Comment by Boldewyn** [comment] 2016-12-01 14:02
Could it be related to this issue? http://jsfiddle.net/dahjelle/zVjfY/

> As reported on StackOverflow and on Microsoft Connect, IE 11 will crash if you set the value of 5 or more input elements to the empty string via Javascript

It should be fixed since 2014, but who knows?

**Comment by Boldewyn** [comment] 2016-12-09 09:44
Closing it for now. I have no further ideas on how to get that error reproduced.

**Closed by Boldewyn** 2016-12-09 09:44 UTC
